### ISSUE TITLE
pixelated images?

### ISSUE THREAD

**Issue by avivajpeyi** [danielgatis/imgcat#14]
Hey! Super cool tool! 

I've installed this on a linux machine. The images appear pixelated while using the default terminal or even [`tabby`](https://tabby.sh/)

Here is an example of using imgcat:

![Screenshot from 2023-08-17 10-17-55](https://github.com/danielgatis/imgcat/assets/15642823/b567974c-b2f4-42b4-8e31-e52100ff3dfb)

And the image opened normally

![Screenshot from 2023-08-17 10-18-35](https://github.com/danielgatis/imgcat/assets/15642823/c57a861b-b769-4946-a1c2-b4e4ab069d88)

**is there any getting around the pixelation?**

**Comment by lpanebr** [comment]
That's what it does, by design. Though I would like to be able to configure how many columns it uses to show the image.
