### ISSUE TITLE
Imgcat and Vifm

### ISSUE THREAD

**Issue by jiDOK** [danielgatis/imgcat#3]
Thanks a lot for Imgcat! It's the only way I have found to preview images in a Windows command prompt.

I am trying to get Imgcat and [Vifm](https://github.com/vifm/vifm) work together on Windows 10, using Imgcat to show images in Vifm's preview pane.

Imgcat works fine by itself in cmd prompt but it does not seem to work from Vifm, producing the error message:
```failed to get the console state: The handle is invalid.``` 

Since I wasn't sure where the problem is rooted, I first asked over at Vifm. From what I understand Vifm expects some kind of output while Imgcat prints directly to the console. 

A workaround was tried but didn't help. Here's the Question over at Vifm's github for reference:
https://github.com/vifm/vifm/issues/671

I am not sure if it is possible on Windows at all, but could Imgcat be made to give Vifm the right output somehow?

**Comment by danielgatis** [comment]
can you provide a simple `vimrc` with `Vifm and imgcat` configured?

**Comment by danielgatis** [comment]
I pushed a new version with this fix: 9e5d4ab673487c09139a705e425d050cd5a37365.

Can you do a test with this version https://github.com/danielgatis/imgcat/releases/tag/v1.0.6?

**Comment by jiDOK** [comment]
I'm not at home, but will do later and report, thanks!

**Comment by jiDOK** [comment]
It seems to be close, but not quite!

I have this in the vifmrc:
```
fileviewer {*.bmp,*.jpg,*.jpeg,*.png,*.gif,*.xpm}
         \ imgcat %"c
```
and I get this result:
![Imgcat01](https://user-images.githubusercontent.com/31440442/117151008-f58a4780-adb8-11eb-8895-9267f8ec6e7e.PNG)
while it should look like this:
![Imgcat02](https://user-images.githubusercontent.com/31440442/117151051-fe7b1900-adb8-11eb-8e04-adfe02ea4d20.PNG)

**Comment by danielgatis** [comment]
looks like the true colors are not supported

**Comment by jiDOK** [comment]
Oh, I see. Xaizek wrote over at Vifm: "I looked at imgcat again and it prints 24-bit escape codes, which Vifm doesn't interpret. So if requirement about output being directly to the console is lifted, you'll still need to add %pd."
Sounds like this is related?

**Comment by danielgatis** [comment]
> Oh, I see. Xaizek wrote over at Vifm: "I looked at imgcat again and it prints 24-bit escape codes, which Vifm doesn't interpret. So if requirement about output being directly to the console is lifted, you'll still need to add %pd."
> Sounds like this is related?

yep! You need to add support to 24-bit color on Vifm to make it works.

**Comment by jiDOK** [comment]
So from what I understand it is not easily possible to add 24-bit color support because of the library Vifm uses on Windows ([PDCurses](https://github.com/wmcbrine/PDCurses)). (Xaizek's answer is in the Vifm-Issue I linked at the top)

So unless you want to add an 8-Bit color mode it's just not compatible on Windows. Since that probably would be a bigger feature request, I'll close the Issue. Thank you for your help!
